networks:
  matt-daemon-net:
    driver: bridge

services:
  matt-daemon:
    build: ./vm
    init: true
    container_name: matt-daemon
    hostname: matt-daemon
    ports:
      - "4242:4242"
    networks:
      - matt-daemon-net
    volumes:
      - ./code:/work
      - ./logs:/var/log/matt_daemon
    working_dir: /work
    command: ["sleep", "infinity"]